/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legyenönismilliomos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.DBModel;
import model.IModel;
import model.Kerdes;

/**
 *
 * @author Kata
 */
public class kerdes_add extends javax.swing.JFrame {

    private IModel model;
    private Vector<Kerdes> kerdesek;

    public kerdes_add() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Legyen Ön is milliomos!");

        String dbURL = "jdbc:mysql://localhost:3306/loim";
        String dbUser = "root";
        String dbPass = "1234";

        try {
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            model = new DBModel(conn);

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addkerdes = new javax.swing.JTextField();
        addvalasz0 = new javax.swing.JTextField();
        addvalasz1 = new javax.swing.JTextField();
        addvalasz2 = new javax.swing.JTextField();
        addvalasz3 = new javax.swing.JTextField();
        addhelyesvalasz = new javax.swing.JTextField();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addkerdes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addkerdes.setText("Ide írhatod az új kérdést.");
        addkerdes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addkerdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addkerdesActionPerformed(evt);
            }
        });

        addvalasz0.setText("Ide írdd a lehetséges választ!");
        addvalasz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvalasz0ActionPerformed(evt);
            }
        });

        addvalasz1.setText("Ide írdd a lehetséges választ!");
        addvalasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvalasz1ActionPerformed(evt);
            }
        });

        addvalasz2.setText("Ide írdd a lehetséges választ!");

        addvalasz3.setText("Ide írdd a lehetséges választ!");

        addhelyesvalasz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addhelyesvalasz.setText("Ide írd be a helyes válasz számát!");

        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setText("Hozzáad");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addkerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addhelyesvalasz, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addvalasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addvalasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addvalasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addvalasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addkerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addvalasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addvalasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addvalasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addvalasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addhelyesvalasz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addvalasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvalasz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addvalasz1ActionPerformed

    private void addvalasz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvalasz0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addvalasz0ActionPerformed

    private void addkerdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addkerdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addkerdesActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        try {
            kerdesek = model.getAllKerdes();
            int id = kerdesek.lastElement().getId() + 1;
            String kerdes = addkerdes.getText();
            String valasz0 = addvalasz0.getText();
            String valasz1 = addvalasz1.getText();
            String valasz2  = addvalasz2.getText();
            String valasz3 = addvalasz3.getText();
            int helyesvalasz = Integer.parseInt(addhelyesvalasz.getText());
            
            model.addKerdes( id, kerdes, valasz0, valasz1, valasz2, valasz3, helyesvalasz);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kerdes_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kerdes_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kerdes_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kerdes_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kerdes_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField addhelyesvalasz;
    private javax.swing.JTextField addkerdes;
    private javax.swing.JTextField addvalasz0;
    private javax.swing.JTextField addvalasz1;
    private javax.swing.JTextField addvalasz2;
    private javax.swing.JTextField addvalasz3;
    // End of variables declaration//GEN-END:variables
}
